apiVersion: apps/v2
kind: Deployment
metadata:
  name: inventario-app-blue
  labels:
    app: inventario-app
    slot: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario-app
      slot: blue
  template:
    metadata:
      labels:
        app: inventario-app
        slot: blue
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/jordyromero03/examenfinaldistribuidos:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "v1"
            - name: APP_COLOR
              value: "blue"
          readinessProbe:
            httpGet: { path: /health, port: 3000}
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet: { path: /health, port: 3000}
            initialDelaySeconds: 5
            periodSeconds: 10
