apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app
  labels:
    app: inventario-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: inventario-app
  template:
    metadata:
      labels:
        app: inventario-app
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/jordyromero03/examenfinaldistribuidos:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: APP_VERSION
              value: "v1"
            - name: APP_COLOR
              value: "blue"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: inventario-secrets
                  key: API_KEY
            - name: STARTUP_DELAY_SECONDS
              value: "15"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
              